name: Build Sykora Android

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Build Android ARM64 Executable
        run: zig build -Doptimize=ReleaseFast -Dtarget=aarch64-linux-android -Dcpu=baseline -Dpie

      - name: Stage Artifact
        run: cp zig-out/bin/sykora sykora-android-aarch64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sykora-android-aarch64
          path: sykora-android-aarch64
